#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM6D v0.3 * Remote controlled switching device                             |
# | Copyright (C) 2020-2021 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | clone                                                                      |
# | Clone libraries from Github                                                |
# +----------------------------------------------------------------------------+

git clone https://github.com/aharshac/StringSplitter.git
